version: '3.1'

services:
  nginx:
    image: nginx
    volumes:
     - ./templates:/etc/nginx/templates
    ports:
     - "8080:80"
    environment:
     - NGINX_HOST=foobar.com
     - NGINX_PORT=80

  mysql:
     image: mysql:5.7
     container_name: mysql
     tty: true
     restart: always
     ports:
      - "3306:3306"
     environment:
      MYSQL_DATABASE: hmh
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
     volumes:
      - dbdata:/var/lib/mysql

      this is cool
      
    
